const Actions = {
	UPDATE_USER : "UPDATE_USER_ACTION",
	DELETE_USER : "DELETE_USER_ACTION",
	
	REGISTER_USER :"REGISTER_USER_ACTION",
	SIGN_IN_USER: "SIGN_IN_USER_ACTION",
	
	CREATE_BOOK : "CREATE_BOOK_ACTION",
	UPDATE_BOOK : "UPDATE_BOOK_ACTION",
	DELETE_BOOK : "DELETE_BOOK_ACTION",

	CREATE_LOAN : "CREATE_LOAN_ACTION",
	UPDATE_LOAN : "UPDATE_LOAN _ACTION",
	CANCEL_LOAN : "CANCEL_LOAN _ACTION",
	DELETE_LOAN : "DELETE_LOAN_ACTION",
	RETURN_LOAN : "RETURN_LOAN_ACTION",

}

export default Actions;